export const COUNTRY_LIST = [
  {
    currency: "AED",
    symbol: "د.إ",
    code: "784",
    name: "Dirham dos Emirados Árabes Unidos",
    country: "UAE",
  },
  {
    currency: "AFN",
    symbol: "Af",
    code: "971",
    name: "Afegão",
    country: "Afeganistão",
  },
  {
    currency: "ALL",
    symbol: "L",
    code: "008",
    name: "Lek",
    country: "Albânia",
  },
  {
    currency: "AMD",
    symbol: "Դ",
    code: "051",
    name: "Dracma Armênio",
    country: "Armênia",
  },
  {
    currency: "AOA",
    symbol: "Kz",
    code: "973",
    name: "Kwanza",
    country: "Angola",
  },
  {
    currency: "ARS",
    symbol: "$",
    code: "032",
    name: "Peso Argentino",
    country: "Argentina",
  },
  {
    currency: "AUD",
    symbol: "$",
    code: "036",
    name: "Dólar Australiano",
    country: "Austrália\nKiribati\nCoconut Islands\nNauru\nTuvalu",
  },
  {
    currency: "AWG",
    symbol: "ƒ",
    code: "533",
    name: "Florin de Aruba",
    country: "Aruba",
  },
  {
    currency: "AZN",
    symbol: "ман",
    code: "944",
    name: "Manat do Azerbaijão",
    country: "Azerbaijão",
  },
  {
    currency: "BAM",
    symbol: "КМ",
    code: "977",
    name: "Konvertibilna Marka",
    country: "Bósnia e Herzegovina",
  },
  {
    currency: "BBD",
    symbol: "$",
    code: "052",
    name: "Dólar de Barbados",
    country: "Barbados",
  },
  {
    currency: "BDT",
    symbol: "৳",
    code: "050",
    name: "Taka",
    country: "Bangladesh",
  },
  {
    currency: "BGN",
    symbol: "лв",
    code: "975",
    name: "Lev Búlgaro",
    country: "Bulgária",
  },
  {
    currency: "BHD",
    symbol: "ب.د",
    code: "048",
    name: "Dinar do Bahrain",
    country: "Bahrain",
  },
  {
    currency: "BIF",
    symbol: "₣",
    code: "108",
    name: "Franco de Burundi",
    country: "Burundi",
  },
  {
    currency: "BMD",
    symbol: "$",
    code: "060",
    name: "Dólar das Bermudas",
    country: "Bermudas",
  },
  {
    currency: "BND",
    symbol: "$",
    code: "096",
    name: "Dólar de Brunei",
    country: "Brunei\nCingapura",
  },
  {
    currency: "BOB",
    symbol: "Bs.",
    code: "068",
    name: "Boliviano",
    country: "Bolívia",
  },
  {
    currency: "BRL",
    symbol: "R$",
    code: "986",
    name: "Real",
    country: "Brasil",
  },
  {
    currency: "BSD",
    symbol: "$",
    code: "044",
    name: "Dólar das Bahamas",
    country: "Bahamas",
  },
  {
    currency: "BTN",
    symbol: "",
    code: "064",
    name: "Ngultrum",
    country: "Butão",
  },
  {
    currency: "BWP",
    symbol: "P",
    code: "072",
    name: "Pula",
    country: "Botswana",
  },
  {
    currency: "BYN",
    symbol: "Br",
    code: "933",
    name: "Rublo Bielorrusso",
    country: "Bielorrússia",
  },
  {
    currency: "BZD",
    symbol: "$",
    code: "084",
    name: "Dólar de Belize",
    country: "Belize",
  },
  {
    currency: "CAD",
    symbol: "$",
    code: "124",
    name: "Dólar Canadense",
    country: "Canadá",
  },
  {
    currency: "CDF",
    symbol: "₣",
    code: "976",
    name: "Franco Congolês",
    country: "Congo (Kinshasa)",
  },
  {
    currency: "CHF",
    symbol: "₣",
    code: "756",
    name: "Franco Suiço",
    country: "Lichtenstein\nSuiça",
  },
  {
    currency: "CLP",
    symbol: "$",
    code: "152",
    name: "Peso Chileno",
    country: "Chile",
  },
  {
    currency: "CNY",
    symbol: "¥",
    code: "156",
    name: "Yuan",
    country: "China",
  },
  {
    currency: "COP",
    symbol: "$",
    code: "170",
    name: "Peso Colombiano",
    country: "Colômbia",
  },
  {
    currency: "CRC",
    symbol: "₡",
    code: "188",
    name: "Colon Costariquenho",
    country: "Costa Rica",
  },
  {
    currency: "CUP",
    symbol: "$",
    code: "192",
    name: "Peso Cubano",
    country: "Cuba",
  },
  {
    currency: "CVE",
    symbol: "$",
    code: "132",
    name: "Escudo de Cabo Verde",
    country: "Cabo Verde",
  },
  {
    currency: "CZK",
    symbol: "Kč",
    code: "203",
    name: "Coroa Tcheca",
    country: "República Tcheca",
  },
  {
    currency: "DJF",
    symbol: "₣",
    code: "262",
    name: "Franco de Djibouti",
    country: "Djibouti",
  },
  {
    currency: "DKK",
    symbol: "kr",
    code: "208",
    name: "Coroa Dinamarquesa",
    country: "Dinamarca",
  },
  {
    currency: "DOP",
    symbol: "$",
    code: "214",
    name: "Peso Dominicano",
    country: "República Dominicana",
  },
  {
    currency: "DZD",
    symbol: "د.ج",
    code: "012",
    name: "Dinar Argelino",
    country: "Argélia",
  },
  {
    currency: "EGP",
    symbol: "£",
    code: "818",
    name: "Libra Egípcia",
    country: "Egito",
  },
  {
    currency: "ERN",
    symbol: "Nfk",
    code: "232",
    name: "Nakfa",
    country: "Eritreia",
  },
  {
    currency: "ETB",
    symbol: "",
    code: "230",
    name: "Birr Etíope",
    country: "Etiópia",
  },
  {
    currency: "EUR",
    symbol: "€",
    code: "978",
    name: "Euro",
    country:
      "Akrotiri e Dhekelia\nAndorra\nÁustria\nBélgica\nChipre\nEstônia\nFinlândia\nFrança\nAlemanha\nGrécia\nIrlanda\nItália\nKosovo\nLatvia\nLituânia\nLuxemburgo\nMalta\nMônaco\nMontenegro\nHolanda\nPortugal\nSan Marino\nEslováquia\nEslovenia\nEspanha\nVaticano",
  },
  {
    currency: "FJD",
    symbol: "$",
    code: "242",
    name: "Dólar de Fiji",
    country: "Fiji",
  },
  {
    currency: "FKP",
    symbol: "£",
    code: "238",
    name: "Libra das Ilhas Falkland",
    country: "Ilhas Falkland",
  },
  {
    currency: "GBP",
    symbol: "£",
    code: "826",
    name: "Libra Esterlina",
    country: "Alderney\nTerritório Britânico do Oceano Índico\nGrã-Bretanha\nIsle of Maine",
  },
  {
    currency: "GEL",
    symbol: "ლ",
    code: "981",
    name: "Lari",
    country: "Georgia\nOssétia do Sul",
  },
  {
    currency: "GHS",
    symbol: "₵",
    code: "936",
    name: "Cedi",
    country: "Gana",
  },
  {
    currency: "GIP",
    symbol: "£",
    code: "292",
    name: "Libra de Gibraltar",
    country: "Gibraltar",
  },
  {
    currency: "GMD",
    symbol: "D",
    code: "270",
    name: "Dalasi",
    country: "Gâmbia",
  },
  {
    currency: "GNF",
    symbol: "₣",
    code: "324",
    name: "Franco de Guiné",
    country: "Guiné",
  },
  {
    currency: "GTQ",
    symbol: "Q",
    code: "320",
    name: "Quetzal",
    country: "Guatemala",
  },
  {
    currency: "GYD",
    symbol: "$",
    code: "328",
    name: "Dólar da Guiana",
    country: "Guiana",
  },
  {
    currency: "HKD",
    symbol: "$",
    code: "344",
    name: "Dólar de Hong Kong",
    country: "Hong Kong",
  },
  {
    currency: "HNL",
    symbol: "L",
    code: "340",
    name: "Lempira",
    country: "Honduras",
  },
  {
    currency: "HRK",
    symbol: "Kn",
    code: "191",
    name: "Kuna Croata",
    country: "Croácia",
  },
  {
    currency: "HTG",
    symbol: "G",
    code: "332",
    name: "Gourde",
    country: "Haiti",
  },
  {
    currency: "HUF",
    symbol: "Ft",
    code: "348",
    name: "Forint",
    country: "Hungria",
  },
  {
    currency: "IDR",
    symbol: "Rp",
    code: "360",
    name: "Rupia",
    country: "Indonésia",
  },
  {
    currency: "ILS",
    symbol: "₪",
    code: "376",
    name: "Novo Shekel Israelense",
    country: "Israel\nPalestina",
  },
  {
    currency: "INR",
    symbol: "₹",
    code: "356",
    name: "Rupia Indiana",
    country: "Butão\nÍndia",
  },
  {
    currency: "IQD",
    symbol: "ع.د",
    code: "368",
    name: "Dinar Iraquiano",
    country: "Iraque",
  },
  {
    currency: "IRR",
    symbol: "﷼",
    code: "364",
    name: "Rial Iraniano",
    country: "Irã",
  },
  {
    currency: "ISK",
    symbol: "Kr",
    code: "352",
    name: "Coroa Islandesa",
    country: "Islândia",
  },
  {
    currency: "JMD",
    symbol: "$",
    code: "388",
    name: "Dólar Jamaicano",
    country: "Jamaica",
  },
  {
    currency: "JOD",
    symbol: "د.ا",
    code: "400",
    name: "Dinar Jordaniano",
    country: "Jordânia",
  },
  {
    currency: "JPY",
    symbol: "¥",
    code: "392",
    name: "Yen",
    country: "Japão",
  },
  {
    currency: "KES",
    symbol: "Sh",
    code: "404",
    name: "Shilling Queniano",
    country: "Quênia",
  },
  {
    currency: "KGS",
    symbol: "",
    code: "417",
    name: "Som",
    country: "Quirguistão",
  },
  {
    currency: "KHR",
    symbol: "៛",
    code: "116",
    name: "Riel",
    country: "Camboja",
  },
  {
    currency: "KPW",
    symbol: "₩",
    code: "408",
    name: "Won Norte-Coreano",
    country: "Coréia do Norte",
  },
  {
    currency: "KRW",
    symbol: "₩",
    code: "410",
    name: "Won Sul-Coreano",
    country: "Coréia do Sul",
  },
  {
    currency: "KWD",
    symbol: "د.ك",
    code: "414",
    name: "Dinar do Kuwait",
    country: "Kuwait",
  },
  {
    currency: "KYD",
    symbol: "$",
    code: "136",
    name: "Dólar das Ilhas Cayman",
    country: "Ilhas Cayman",
  },
  {
    currency: "KZT",
    symbol: "〒",
    code: "398",
    name: "Tenge",
    country: "Cazaquistão",
  },
  {
    currency: "LAK",
    symbol: "₭",
    code: "418",
    name: "Kip",
    country: "Laos",
  },
  {
    currency: "LBP",
    symbol: "ل.ل",
    code: "422",
    name: "Libra Libanesa",
    country: "Líbano",
  },
  {
    currency: "LKR",
    symbol: "Rs",
    code: "144",
    name: "Rupia do Sri Lanka",
    country: "Sri Lanka",
  },
  {
    currency: "LRD",
    symbol: "$",
    code: "430",
    name: "Dólar Liberiano",
    country: "Libéria",
  },
  {
    currency: "LSL",
    symbol: "L",
    code: "426",
    name: "Loti",
    country: "Lesoto",
  },
  {
    currency: "LYD",
    symbol: "ل.د",
    code: "434",
    name: "Dinar da Líbia",
    country: "Líbia",
  },
  {
    currency: "MAD",
    symbol: "د.م.",
    code: "504",
    name: "Dirham Marroquino",
    country: "Marrocos",
  },
  {
    currency: "MDL",
    symbol: "L",
    code: "498",
    name: "Leu Moldavo",
    country: "Moldova",
  },
  {
    currency: "MGA",
    symbol: "",
    code: "969",
    name: "Ariary Malgaxe",
    country: "Madagascar",
  },
  {
    currency: "MKD",
    symbol: "ден",
    code: "807",
    name: "Denar",
    country: "Macedônia",
  },
  {
    currency: "MMK",
    symbol: "K",
    code: "104",
    name: "Kyat",
    country: "Myanmar (Burma)",
  },
  {
    currency: "MNT",
    symbol: "₮",
    code: "496",
    name: "Tugrik",
    country: "Mongólia",
  },
  {
    currency: "MOP",
    symbol: "P",
    code: "446",
    name: "Pataca",
    country: "Macau",
  },
  {
    currency: "MRU",
    symbol: "UM",
    code: "929",
    name: "Ouguiya",
    country: "Mauritânia",
  },
  {
    currency: "MUR",
    symbol: "₨",
    code: "480",
    name: "Rupia de Maurício",
    country: "República de Maurício",
  },
  {
    currency: "MVR",
    symbol: "ރ.",
    code: "462",
    name: "Rufiyaa",
    country: "Maldivas",
  },
  {
    currency: "MWK",
    symbol: "MK",
    code: "454",
    name: "Kwacha",
    country: "Malavi",
  },
  {
    currency: "MXN",
    symbol: "$",
    code: "484",
    name: "Peso Mexicano",
    country: "México",
  },
  {
    currency: "MYR",
    symbol: "RM",
    code: "458",
    name: "Ringgit Malaio",
    country: "Malásia",
  },
  {
    currency: "MZN",
    symbol: "MTn",
    code: "943",
    name: "Metical",
    country: "Moçambique",
  },
  {
    currency: "NAD",
    symbol: "$",
    code: "516",
    name: "Dólar da Namíbia",
    country: "Namíbia",
  },
  {
    currency: "NGN",
    symbol: "₦",
    code: "566",
    name: "Naira",
    country: "Nigéria",
  },
  {
    currency: "NIO",
    symbol: "C$",
    code: "558",
    name: "Oro de Cordoba",
    country: "Nicarágua",
  },
  {
    currency: "NOK",
    symbol: "kr",
    code: "578",
    name: "Coroa Norueguesa",
    country: "Noruega",
  },
  {
    currency: "NPR",
    symbol: "₨",
    code: "524",
    name: "Rupia Nepalesa",
    country: "Nepal",
  },
  {
    currency: "NZD",
    symbol: "$",
    code: "554",
    name: "Dólar Neozelandês",
    country: "Ilhas Cook\nNova Zelândia\nNiue\nIlha Pitcairn",
  },
  {
    currency: "OMR",
    symbol: "ر.ع.",
    code: "512",
    name: "Rial Omani",
    country: "Omã",
  },
  {
    currency: "PAB",
    symbol: "B/.",
    code: "590",
    name: "Balboa",
    country: "Panamá",
  },
  {
    currency: "PEN",
    symbol: "S/.",
    code: "604",
    name: "Novo Sol",
    country: "Peru",
  },
  {
    currency: "PGK",
    symbol: "K",
    code: "598",
    name: "Kina",
    country: "Papua Nova Guiné",
  },
  {
    currency: "PHP",
    symbol: "₱",
    code: "608",
    name: "Peso Filipinio",
    country: "Filipinas",
  },
  {
    currency: "PKR",
    symbol: "₨",
    code: "586",
    name: "Rupia Paquistanesa",
    country: "Paquistão",
  },
  {
    currency: "PLN",
    symbol: "zł",
    code: "985",
    name: "PZloty",
    country: "Polônia",
  },
  {
    currency: "PYG",
    symbol: "₲",
    code: "600",
    name: "Guarani",
    country: "Paraguai",
  },
  {
    currency: "QAR",
    symbol: "ر.ق",
    code: "634",
    name: "Qatari Rial",
    country: "Catar",
  },
  {
    currency: "RON",
    symbol: "L",
    code: "946",
    name: "Leu",
    country: "Romênia",
  },
  {
    currency: "RSD",
    symbol: "din",
    code: "941",
    name: "Dinar Sérvio",
    country: "Kosovo\nSérvia",
  },
  {
    currency: "RUB",
    symbol: "р.",
    code: "643",
    name: "Rublo Russo",
    country: "Rússia\nOssétia do Sul",
  },
  {
    currency: "RWF",
    symbol: "₣",
    code: "646",
    name: "Franco de Ruanda",
    country: "Ruanda",
  },
  {
    currency: "SAR",
    symbol: "ر.س",
    code: "682",
    name: "Riyal Saudita",
    country: "Arábia Saudita",
  },
  {
    currency: "SBD",
    symbol: "$",
    code: "090",
    name: "Dólar das Ilhas Salomão",
    country: "Ilhas Salomão",
  },
  {
    currency: "SCR",
    symbol: "₨",
    code: "690",
    name: "Rúpia do Seicheles",
    country: "Seicheles",
  },
  {
    currency: "SDG",
    symbol: "£",
    code: "938",
    name: "Libra Sudanesa",
    country: "Sudão",
  },
  {
    currency: "SEK",
    symbol: "kr",
    code: "752",
    name: "Coroa Sueca",
    country: "Suécia",
  },
  {
    currency: "SGD",
    symbol: "$",
    code: "702",
    name: "Dólar de Cingapura",
    country: "Brunei\nCingapura",
  },
  {
    currency: "SHP",
    symbol: "£",
    code: "654",
    name: "Libra de Santa Helena",
    country: "Ascension Island\nSanta Helena\nTristan da Cunha",
  },
  {
    currency: "SLL",
    symbol: "Le",
    code: "694",
    name: "Leone",
    country: "Serra Leoa",
  },
  {
    currency: "SOS",
    symbol: "Sh",
    code: "706",
    name: "Shilling Somali",
    country: "Somália",
  },
  {
    currency: "SRD",
    symbol: "$",
    code: "968",
    name: "Dólar do Suriname",
    country: "Suriname",
  },
  {
    currency: "STN",
    symbol: "Db",
    code: "930",
    name: "Dobra",
    country: "São Tomé e Príncipe",
  },
  {
    currency: "SYP",
    symbol: "ل.س",
    code: "760",
    name: "Libra Síria",
    country: "Síria",
  },
  {
    currency: "SZL",
    symbol: "L",
    code: "748",
    name: "Lilangeni",
    country: "Suazilândia",
  },
  {
    currency: "THB",
    symbol: "฿",
    code: "764",
    name: "Baht",
    country: "Tailândia",
  },
  {
    currency: "TJS",
    symbol: "ЅМ",
    code: "972",
    name: "Somoni",
    country: "Tajiquistão",
  },
  {
    currency: "TMT",
    symbol: "m",
    code: "934",
    name: "Manat",
    country: "Turquemenistão",
  },
  {
    currency: "TND",
    symbol: "د.ت",
    code: "788",
    name: "Dinar Tunisiano",
    country: "Tunísia",
  },
  {
    currency: "TOP",
    symbol: "T$",
    code: "776",
    name: "Pa’anga",
    country: "Tonga",
  },
  {
    currency: "TRY",
    symbol: "₤",
    code: "949",
    name: "Lira Turca",
    country: "Chipre do Norte\nTurquia",
  },
  {
    currency: "TTD",
    symbol: "$",
    code: "780",
    name: "Dólar de Trinidad e Tobago",
    country: "Trinidad e Tobago",
  },
  {
    currency: "TWD",
    symbol: "$",
    code: "901",
    name: "Dólar de Taiwan",
    country: "Taiwan",
  },
  {
    currency: "TZS",
    symbol: "Sh",
    code: "834",
    name: "Shilling da Tanzânia",
    country: "Tanzânia",
  },
  {
    currency: "UAH",
    symbol: "₴",
    code: "980",
    name: "Hryvnia",
    country: "Ucrânia",
  },
  {
    currency: "UGX",
    symbol: "Sh",
    code: "800",
    name: "Shilling de Uganda",
    country: "Uganda",
  },
  {
    currency: "USD",
    symbol: "$",
    code: "840",
    name: "Dólar Norte-Americano",
    country:
      "Samoa Americana\nTerritório Britânico do Oceano Índico\nIlhas Virgens Britânicas\nGuam\nHaiti\nMarshall Islands\nMicronésia\nIlhas Marianas do Norte\nIlhas Remotas do Pacífico\nPalau\nPanamá\nPorto Rico\nIlhas Turcas e Caicos\nEstados Unidos da América\nIlhas Virgens dos EE.UU.",
  },
  {
    currency: "UYU",
    symbol: "$",
    code: "858",
    name: "Peso Uruguaio",
    country: "Uruguai",
  },
  {
    currency: "UZS",
    symbol: "",
    code: "860",
    name: "Sum Uzbequistão",
    country: "Uzbequistão",
  },
  {
    currency: "VEF",
    symbol: "Bs F",
    code: "937",
    name: "Bolivar Venezuelano",
    country: "Venezuela",
  },
  {
    currency: "VND",
    symbol: "₫",
    code: "704",
    name: "Dong",
    country: "Vietnã",
  },
  {
    currency: "VUV",
    symbol: "Vt",
    code: "548",
    name: "Vatu",
    country: "Vanuatu",
  },
  {
    currency: "WST",
    symbol: "T",
    code: "882",
    name: "Tala",
    country: "Samoa",
  },
  {
    currency: "YER",
    symbol: "﷼",
    code: "886",
    name: "Rial Iemnita",
    country: "Iémen",
  },
  {
    currency: "ZAR",
    symbol: "R",
    code: "710",
    name: "Rand",
    country: "Lesoto\nNamíbia\nÁfrica do Sul",
  },
  {
    currency: "ZMW",
    symbol: "ZK",
    code: "967",
    name: "Kwacha Zambiano",
    country: "Zâmbia",
  },
  {
    currency: "ZWL",
    symbol: "$",
    code: "932",
    name: "Dólar do Zimbábue",
    country: "Zimbábue",
  },
];
